name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cancel-previous:
    name: Cancel Previous
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Build
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: cancel-previous
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2.4.0
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: Lint
        run: make clean lint

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: cancel-previous
    env:
      PULL_REQUEST: true
      CODECOV_TOKEN: ${{ secrets.CODECOV_REPO_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup JDK
        uses: actions/setup-java@v2.4.0
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: Test
        run: make test
